let CLOUD_FILIPIZEN_SERVER_IP =
	import.meta.env.VITE_CLOUD_FILIPIZEN_SERVER_IP || '172.28.222.202:5000';

let CLOUD_GDX_NODE_IP = import.meta.env.VITE_CLOUD_GDX_NODE_IP || '172.28.222.202:3000';

CLOUD_FILIPIZEN_SERVER_IP = process.env.CLOUD_FILIPIZEN_SERVER_IP || CLOUD_FILIPIZEN_SERVER_IP;
CLOUD_GDX_NODE_IP = process.env.CLOUD_GDX_NODE_IP || CLOUD_GDX_NODE_IP;

console.log('CLOUD_FILIPIZEN_SERVER_IP:', CLOUD_FILIPIZEN_SERVER_IP);
console.log('CLOUD_GDX_NODE_IP:', CLOUD_GDX_NODE_IP);

export const cloudFilipizenServerUrl = `http://${CLOUD_FILIPIZEN_SERVER_IP}`;

export const cloudGdxNodeServerIp = CLOUD_GDX_NODE_IP;

export const cloudGdxNodeServerUrl = `http://${CLOUD_GDX_NODE_IP}`;
