let CLOUD_FILIPIZEN_SERVER_HOST =
	import.meta.env.VITE_CLOUD_FILIPIZEN_SERVER_HOST || 'http://172.28.222.202:5000';

let CLOUD_GDX_NODE_HOST = import.meta.env.VITE_CLOUD_GDX_NODE_HOST || 'http://172.28.222.202:3000';

let CLOUD_PROXY_SERVER_HOST =
	import.meta.env.VITE_CLOUD_PROXY_SERVER_HOST || 'http://172.28.222.202:90';

CLOUD_FILIPIZEN_SERVER_HOST =
	process.env.CLOUD_FILIPIZEN_SERVER_HOST || CLOUD_FILIPIZEN_SERVER_HOST;
CLOUD_GDX_NODE_HOST = process.env.CLOUD_GDX_NODE_HOST || CLOUD_GDX_NODE_HOST;
CLOUD_PROXY_SERVER_HOST = process.env.CLOUD_PROXY_SERVER_HOST || CLOUD_PROXY_SERVER_HOST;

console.log('CLOUD_FILIPIZEN_SERVER_HOST:', CLOUD_FILIPIZEN_SERVER_HOST);
console.log('CLOUD_GDX_NODE_HOST:', CLOUD_GDX_NODE_HOST);
console.log('CLOUD_PROXY_SERVER_HOST:', CLOUD_PROXY_SERVER_HOST);

export const cloudProxyServerHost = CLOUD_PROXY_SERVER_HOST;
export const cloudFilipizenServerHost = CLOUD_FILIPIZEN_SERVER_HOST;
export const cloudGdxNodeServerHost = CLOUD_GDX_NODE_HOST;
